name = "Ilina Yozova"
license = "MIT"
licenselink = "https://github.com/gurusabarish/hugo-profile/blob/master/LICENSE"
description = "SOMETHING"
homepage = "https://ilinayozova.github.io"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

